// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alisms.proto

package alisms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SMSVerficationCodeData struct {
	SignName             string   `protobuf:"bytes,1,opt,name=sign_name,json=signName,proto3" json:"sign_name,omitempty"`
	PhoneNumbers         string   `protobuf:"bytes,2,opt,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	TemplateCode         string   `protobuf:"bytes,3,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	TemplateParam        string   `protobuf:"bytes,4,opt,name=template_param,json=templateParam,proto3" json:"template_param,omitempty"`
	SmsUpExtendCode      string   `protobuf:"bytes,5,opt,name=sms_up_extend_code,json=smsUpExtendCode,proto3" json:"sms_up_extend_code,omitempty"`
	OutId                string   `protobuf:"bytes,6,opt,name=out_id,json=outId,proto3" json:"out_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationCodeData) Reset()         { *m = SMSVerficationCodeData{} }
func (m *SMSVerficationCodeData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationCodeData) ProtoMessage()    {}
func (*SMSVerficationCodeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_63ecbde3248dbaa9, []int{0}
}
func (m *SMSVerficationCodeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationCodeData.Unmarshal(m, b)
}
func (m *SMSVerficationCodeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationCodeData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationCodeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationCodeData.Merge(dst, src)
}
func (m *SMSVerficationCodeData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationCodeData.Size(m)
}
func (m *SMSVerficationCodeData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationCodeData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationCodeData proto.InternalMessageInfo

func (m *SMSVerficationCodeData) GetSignName() string {
	if m != nil {
		return m.SignName
	}
	return ""
}

func (m *SMSVerficationCodeData) GetPhoneNumbers() string {
	if m != nil {
		return m.PhoneNumbers
	}
	return ""
}

func (m *SMSVerficationCodeData) GetTemplateCode() string {
	if m != nil {
		return m.TemplateCode
	}
	return ""
}

func (m *SMSVerficationCodeData) GetTemplateParam() string {
	if m != nil {
		return m.TemplateParam
	}
	return ""
}

func (m *SMSVerficationCodeData) GetSmsUpExtendCode() string {
	if m != nil {
		return m.SmsUpExtendCode
	}
	return ""
}

func (m *SMSVerficationCodeData) GetOutId() string {
	if m != nil {
		return m.OutId
	}
	return ""
}

type SMSVerficationCodeCheckData struct {
	PhoneNumbers         string   `protobuf:"bytes,1,opt,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	Vcode                string   `protobuf:"bytes,2,opt,name=vcode,proto3" json:"vcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationCodeCheckData) Reset()         { *m = SMSVerficationCodeCheckData{} }
func (m *SMSVerficationCodeCheckData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationCodeCheckData) ProtoMessage()    {}
func (*SMSVerficationCodeCheckData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_63ecbde3248dbaa9, []int{1}
}
func (m *SMSVerficationCodeCheckData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationCodeCheckData.Unmarshal(m, b)
}
func (m *SMSVerficationCodeCheckData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationCodeCheckData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationCodeCheckData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationCodeCheckData.Merge(dst, src)
}
func (m *SMSVerficationCodeCheckData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationCodeCheckData.Size(m)
}
func (m *SMSVerficationCodeCheckData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationCodeCheckData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationCodeCheckData proto.InternalMessageInfo

func (m *SMSVerficationCodeCheckData) GetPhoneNumbers() string {
	if m != nil {
		return m.PhoneNumbers
	}
	return ""
}

func (m *SMSVerficationCodeCheckData) GetVcode() string {
	if m != nil {
		return m.Vcode
	}
	return ""
}

type SMSVerficationResponseData struct {
	ReturnCode           int64    `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationResponseData) Reset()         { *m = SMSVerficationResponseData{} }
func (m *SMSVerficationResponseData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationResponseData) ProtoMessage()    {}
func (*SMSVerficationResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_63ecbde3248dbaa9, []int{2}
}
func (m *SMSVerficationResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationResponseData.Unmarshal(m, b)
}
func (m *SMSVerficationResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationResponseData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationResponseData.Merge(dst, src)
}
func (m *SMSVerficationResponseData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationResponseData.Size(m)
}
func (m *SMSVerficationResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationResponseData proto.InternalMessageInfo

func (m *SMSVerficationResponseData) GetReturnCode() int64 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func (m *SMSVerficationResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SMSVerficationResponseData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SMSVerficationQueryData struct {
	PhoneNumbers         string   `protobuf:"bytes,1,opt,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	SendDate             string   `protobuf:"bytes,2,opt,name=send_date,json=sendDate,proto3" json:"send_date,omitempty"`
	PageSize             string   `protobuf:"bytes,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CurrentPage          string   `protobuf:"bytes,4,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	BizId                string   `protobuf:"bytes,5,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationQueryData) Reset()         { *m = SMSVerficationQueryData{} }
func (m *SMSVerficationQueryData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationQueryData) ProtoMessage()    {}
func (*SMSVerficationQueryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_63ecbde3248dbaa9, []int{3}
}
func (m *SMSVerficationQueryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationQueryData.Unmarshal(m, b)
}
func (m *SMSVerficationQueryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationQueryData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationQueryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationQueryData.Merge(dst, src)
}
func (m *SMSVerficationQueryData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationQueryData.Size(m)
}
func (m *SMSVerficationQueryData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationQueryData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationQueryData proto.InternalMessageInfo

func (m *SMSVerficationQueryData) GetPhoneNumbers() string {
	if m != nil {
		return m.PhoneNumbers
	}
	return ""
}

func (m *SMSVerficationQueryData) GetSendDate() string {
	if m != nil {
		return m.SendDate
	}
	return ""
}

func (m *SMSVerficationQueryData) GetPageSize() string {
	if m != nil {
		return m.PageSize
	}
	return ""
}

func (m *SMSVerficationQueryData) GetCurrentPage() string {
	if m != nil {
		return m.CurrentPage
	}
	return ""
}

func (m *SMSVerficationQueryData) GetBizId() string {
	if m != nil {
		return m.BizId
	}
	return ""
}

type SMSVerficationQueryResponseData struct {
	ReturnCode           int64    `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationQueryResponseData) Reset()         { *m = SMSVerficationQueryResponseData{} }
func (m *SMSVerficationQueryResponseData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationQueryResponseData) ProtoMessage()    {}
func (*SMSVerficationQueryResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_63ecbde3248dbaa9, []int{4}
}
func (m *SMSVerficationQueryResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationQueryResponseData.Unmarshal(m, b)
}
func (m *SMSVerficationQueryResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationQueryResponseData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationQueryResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationQueryResponseData.Merge(dst, src)
}
func (m *SMSVerficationQueryResponseData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationQueryResponseData.Size(m)
}
func (m *SMSVerficationQueryResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationQueryResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationQueryResponseData proto.InternalMessageInfo

func (m *SMSVerficationQueryResponseData) GetReturnCode() int64 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func (m *SMSVerficationQueryResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SMSVerficationQueryResponseData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*SMSVerficationCodeData)(nil), "alisms.SMSVerficationCodeData")
	proto.RegisterType((*SMSVerficationCodeCheckData)(nil), "alisms.SMSVerficationCodeCheckData")
	proto.RegisterType((*SMSVerficationResponseData)(nil), "alisms.SMSVerficationResponseData")
	proto.RegisterType((*SMSVerficationQueryData)(nil), "alisms.SMSVerficationQueryData")
	proto.RegisterType((*SMSVerficationQueryResponseData)(nil), "alisms.SMSVerficationQueryResponseData")
}

func init() { proto.RegisterFile("alisms.proto", fileDescriptor_alisms_63ecbde3248dbaa9) }

var fileDescriptor_alisms_63ecbde3248dbaa9 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0xdb, 0x1a, 0xba, 0xdb, 0x02, 0x92, 0x61, 0x10, 0x75, 0x12, 0x85, 0x4c, 0x08, 0x24,
	0xa4, 0x3d, 0xc0, 0x2f, 0x40, 0x1b, 0x0f, 0x7b, 0x60, 0x1a, 0xad, 0x40, 0x88, 0x97, 0xc8, 0x8d,
	0x2f, 0xad, 0xb5, 0xf9, 0x43, 0xfe, 0x98, 0xa0, 0x3f, 0x6b, 0x3f, 0x8b, 0x5f, 0x81, 0x6c, 0x27,
	0x11, 0xa5, 0x01, 0xed, 0x85, 0xb7, 0xf8, 0xf8, 0xf8, 0x9e, 0x7b, 0xcf, 0xb1, 0x03, 0x63, 0x7a,
	0xc5, 0xad, 0xb0, 0xc7, 0xda, 0x28, 0xa7, 0x48, 0x9e, 0x56, 0xe5, 0xcf, 0x0c, 0x1e, 0xcf, 0x3f,
	0xcc, 0x3f, 0xa3, 0xf9, 0xc6, 0x6b, 0xea, 0xb8, 0x92, 0x27, 0x8a, 0xe1, 0x29, 0x75, 0x94, 0x1c,
	0xc2, 0xbe, 0xe5, 0x4b, 0x59, 0x49, 0x2a, 0xb0, 0xc8, 0x9e, 0x65, 0xaf, 0xf6, 0x67, 0xc3, 0x00,
	0x9c, 0x53, 0x81, 0xe4, 0x08, 0xee, 0xe9, 0x95, 0x92, 0x58, 0x49, 0x2f, 0x16, 0x68, 0x6c, 0xb1,
	0x13, 0x09, 0xe3, 0x08, 0x9e, 0x27, 0x2c, 0x90, 0x1c, 0x0a, 0x7d, 0x45, 0x1d, 0x56, 0xb5, 0x62,
	0x58, 0xec, 0x26, 0x52, 0x0b, 0x06, 0x29, 0xf2, 0x02, 0xee, 0x77, 0x24, 0x4d, 0x0d, 0x15, 0xc5,
	0x5e, 0x64, 0x75, 0x47, 0x2f, 0x02, 0x48, 0x5e, 0x03, 0xb1, 0xc2, 0x56, 0x5e, 0x57, 0xf8, 0xdd,
	0xa1, 0x64, 0xa9, 0xe0, 0x20, 0x52, 0x1f, 0x58, 0x61, 0x3f, 0xe9, 0xf7, 0x11, 0x8f, 0x35, 0x0f,
	0x20, 0x57, 0xde, 0x55, 0x9c, 0x15, 0x79, 0x24, 0x0c, 0x94, 0x77, 0x67, 0xac, 0xfc, 0x02, 0x87,
	0xdb, 0xb3, 0x9e, 0xac, 0xb0, 0xbe, 0x8c, 0x03, 0x6f, 0xcd, 0x94, 0xf5, 0xcc, 0xf4, 0x08, 0x06,
	0xd7, 0x51, 0x3a, 0x0d, 0x9c, 0x16, 0xe5, 0x25, 0x4c, 0x36, 0x2b, 0xcf, 0xd0, 0x6a, 0x25, 0x6d,
	0x72, 0x72, 0x0a, 0x23, 0x83, 0xce, 0x1b, 0x99, 0x9a, 0x0e, 0x65, 0x77, 0x67, 0x90, 0xa0, 0xd8,
	0x6f, 0x01, 0x77, 0x05, 0x5a, 0x4b, 0x97, 0x6d, 0xd9, 0x76, 0x49, 0x08, 0xec, 0x31, 0xea, 0x68,
	0xe3, 0x5c, 0xfc, 0x2e, 0x6f, 0x32, 0x78, 0xb2, 0xa9, 0xf6, 0xd1, 0xa3, 0xf9, 0x71, 0xfb, 0x19,
	0x42, 0xb2, 0xc1, 0x42, 0x46, 0x5d, 0x2b, 0x38, 0x0c, 0xc0, 0x29, 0x75, 0x18, 0x36, 0x35, 0x5d,
	0x62, 0x65, 0xf9, 0xba, 0x0d, 0x6c, 0x18, 0x80, 0x39, 0x5f, 0x23, 0x79, 0x0e, 0xe3, 0xda, 0x1b,
	0x83, 0xd2, 0x55, 0x01, 0x6b, 0xa2, 0x1a, 0x35, 0xd8, 0x45, 0xe8, 0xf8, 0x00, 0xf2, 0x05, 0x5f,
	0x07, 0xef, 0x53, 0x38, 0x83, 0x05, 0x5f, 0x9f, 0xb1, 0x52, 0xc3, 0xb4, 0xa7, 0xe7, 0xff, 0x68,
	0xd3, 0x9b, 0x9b, 0x1d, 0x18, 0xbd, 0xf3, 0x6e, 0x35, 0x47, 0x73, 0xcd, 0x6b, 0x24, 0x5f, 0x81,
	0x6c, 0xa7, 0x4f, 0x9e, 0x1e, 0x37, 0xef, 0xa2, 0xff, 0x15, 0x4c, 0xca, 0xfe, 0xfd, 0xdf, 0x1b,
	0x2f, 0xef, 0x10, 0xf6, 0x67, 0x22, 0xdd, 0xcd, 0x22, 0x47, 0x7f, 0x17, 0xe8, 0xae, 0xde, 0x2d,
	0x55, 0x28, 0x3c, 0xec, 0xf1, 0x90, 0x4c, 0xfb, 0x0f, 0x77, 0x97, 0x62, 0xf2, 0xf2, 0x1f, 0x84,
	0x4d, 0x89, 0x45, 0x1e, 0x7f, 0x0f, 0x6f, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xd9, 0x31,
	0xf7, 0x2e, 0x04, 0x00, 0x00,
}
