// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alisms.proto

package alisms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SMSVerficationCodeData struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationCodeData) Reset()         { *m = SMSVerficationCodeData{} }
func (m *SMSVerficationCodeData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationCodeData) ProtoMessage()    {}
func (*SMSVerficationCodeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_6b7641b6e9595d7e, []int{0}
}
func (m *SMSVerficationCodeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationCodeData.Unmarshal(m, b)
}
func (m *SMSVerficationCodeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationCodeData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationCodeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationCodeData.Merge(dst, src)
}
func (m *SMSVerficationCodeData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationCodeData.Size(m)
}
func (m *SMSVerficationCodeData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationCodeData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationCodeData proto.InternalMessageInfo

func (m *SMSVerficationCodeData) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type SMSVerficationCodeCheckData struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Vcode                string   `protobuf:"bytes,2,opt,name=vcode,proto3" json:"vcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationCodeCheckData) Reset()         { *m = SMSVerficationCodeCheckData{} }
func (m *SMSVerficationCodeCheckData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationCodeCheckData) ProtoMessage()    {}
func (*SMSVerficationCodeCheckData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_6b7641b6e9595d7e, []int{1}
}
func (m *SMSVerficationCodeCheckData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationCodeCheckData.Unmarshal(m, b)
}
func (m *SMSVerficationCodeCheckData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationCodeCheckData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationCodeCheckData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationCodeCheckData.Merge(dst, src)
}
func (m *SMSVerficationCodeCheckData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationCodeCheckData.Size(m)
}
func (m *SMSVerficationCodeCheckData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationCodeCheckData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationCodeCheckData proto.InternalMessageInfo

func (m *SMSVerficationCodeCheckData) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SMSVerficationCodeCheckData) GetVcode() string {
	if m != nil {
		return m.Vcode
	}
	return ""
}

type SMSVerficationQueryData struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Vcode                string   `protobuf:"bytes,2,opt,name=vcode,proto3" json:"vcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationQueryData) Reset()         { *m = SMSVerficationQueryData{} }
func (m *SMSVerficationQueryData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationQueryData) ProtoMessage()    {}
func (*SMSVerficationQueryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_6b7641b6e9595d7e, []int{2}
}
func (m *SMSVerficationQueryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationQueryData.Unmarshal(m, b)
}
func (m *SMSVerficationQueryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationQueryData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationQueryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationQueryData.Merge(dst, src)
}
func (m *SMSVerficationQueryData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationQueryData.Size(m)
}
func (m *SMSVerficationQueryData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationQueryData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationQueryData proto.InternalMessageInfo

func (m *SMSVerficationQueryData) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SMSVerficationQueryData) GetVcode() string {
	if m != nil {
		return m.Vcode
	}
	return ""
}

type SMSVerficationResponseData struct {
	ReturnCode           int64    `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationResponseData) Reset()         { *m = SMSVerficationResponseData{} }
func (m *SMSVerficationResponseData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationResponseData) ProtoMessage()    {}
func (*SMSVerficationResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_6b7641b6e9595d7e, []int{3}
}
func (m *SMSVerficationResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationResponseData.Unmarshal(m, b)
}
func (m *SMSVerficationResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationResponseData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationResponseData.Merge(dst, src)
}
func (m *SMSVerficationResponseData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationResponseData.Size(m)
}
func (m *SMSVerficationResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationResponseData proto.InternalMessageInfo

func (m *SMSVerficationResponseData) GetReturnCode() int64 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func (m *SMSVerficationResponseData) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SMSVerficationResponseData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SMSVerficationQueryResponseData struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Vcode                string   `protobuf:"bytes,2,opt,name=vcode,proto3" json:"vcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSVerficationQueryResponseData) Reset()         { *m = SMSVerficationQueryResponseData{} }
func (m *SMSVerficationQueryResponseData) String() string { return proto.CompactTextString(m) }
func (*SMSVerficationQueryResponseData) ProtoMessage()    {}
func (*SMSVerficationQueryResponseData) Descriptor() ([]byte, []int) {
	return fileDescriptor_alisms_6b7641b6e9595d7e, []int{4}
}
func (m *SMSVerficationQueryResponseData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSVerficationQueryResponseData.Unmarshal(m, b)
}
func (m *SMSVerficationQueryResponseData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSVerficationQueryResponseData.Marshal(b, m, deterministic)
}
func (dst *SMSVerficationQueryResponseData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSVerficationQueryResponseData.Merge(dst, src)
}
func (m *SMSVerficationQueryResponseData) XXX_Size() int {
	return xxx_messageInfo_SMSVerficationQueryResponseData.Size(m)
}
func (m *SMSVerficationQueryResponseData) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSVerficationQueryResponseData.DiscardUnknown(m)
}

var xxx_messageInfo_SMSVerficationQueryResponseData proto.InternalMessageInfo

func (m *SMSVerficationQueryResponseData) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SMSVerficationQueryResponseData) GetVcode() string {
	if m != nil {
		return m.Vcode
	}
	return ""
}

func init() {
	proto.RegisterType((*SMSVerficationCodeData)(nil), "alisms.SMSVerficationCodeData")
	proto.RegisterType((*SMSVerficationCodeCheckData)(nil), "alisms.SMSVerficationCodeCheckData")
	proto.RegisterType((*SMSVerficationQueryData)(nil), "alisms.SMSVerficationQueryData")
	proto.RegisterType((*SMSVerficationResponseData)(nil), "alisms.SMSVerficationResponseData")
	proto.RegisterType((*SMSVerficationQueryResponseData)(nil), "alisms.SMSVerficationQueryResponseData")
}

func init() { proto.RegisterFile("alisms.proto", fileDescriptor_alisms_6b7641b6e9595d7e) }

var fileDescriptor_alisms_6b7641b6e9595d7e = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0x77, 0x9b, 0x56, 0x7c, 0xf3, 0xf4, 0x94, 0x59, 0x2a, 0x58, 0x89, 0x07, 0x3d, 0x0d, 0xd1,
	0x4f, 0x20, 0x13, 0x3c, 0x88, 0x88, 0x2d, 0x78, 0xf0, 0x22, 0x59, 0xfb, 0x74, 0x61, 0x6b, 0x33,
	0x92, 0x74, 0xe0, 0xd7, 0xf2, 0x13, 0xca, 0xd2, 0xad, 0x18, 0x17, 0x87, 0xee, 0xd6, 0xdf, 0x6b,
	0x7e, 0x7f, 0xf2, 0x7e, 0x81, 0x7d, 0x3e, 0x11, 0xba, 0xd0, 0xfd, 0xa9, 0x92, 0x46, 0x62, 0x50,
	0x23, 0x76, 0x09, 0xbd, 0xf4, 0x21, 0x7d, 0x26, 0xf5, 0x26, 0x32, 0x6e, 0x84, 0x2c, 0x07, 0x32,
	0xa7, 0x5b, 0x6e, 0x38, 0xf6, 0x20, 0x28, 0xe4, 0x50, 0x4c, 0x28, 0x6c, 0x9d, 0xb6, 0x2e, 0xf6,
	0x92, 0x05, 0x62, 0xf7, 0x70, 0xbc, 0xca, 0x18, 0x8c, 0x28, 0x1b, 0xaf, 0xa3, 0xe1, 0x21, 0xec,
	0xcc, 0x32, 0x99, 0x53, 0xd8, 0xb6, 0xe3, 0x1a, 0xb0, 0x3b, 0x38, 0x72, 0xc5, 0x9e, 0x2a, 0x52,
	0x1f, 0x1b, 0x08, 0x8d, 0x21, 0x72, 0x85, 0x12, 0xd2, 0x53, 0x59, 0xea, 0xfa, 0x2e, 0x31, 0x74,
	0x15, 0x99, 0x4a, 0x95, 0xaf, 0x96, 0x39, 0x17, 0xec, 0x24, 0x50, 0x8f, 0xe6, 0xf1, 0x31, 0x84,
	0xdd, 0x82, 0xb4, 0xe6, 0xef, 0x4b, 0xd9, 0x25, 0x44, 0x84, 0xed, 0x9c, 0x1b, 0x1e, 0x76, 0xec,
	0xd8, 0x7e, 0xb3, 0x47, 0x88, 0x3d, 0xa9, 0x1d, 0xc7, 0x7f, 0xa5, 0xbf, 0xfa, 0x6c, 0x43, 0xf7,
	0xa6, 0x32, 0xa3, 0x94, 0xd4, 0x4c, 0x64, 0x84, 0x2f, 0x80, 0xab, 0x3b, 0xc6, 0x93, 0xfe, 0xa2,
	0x42, 0x7f, 0x63, 0x11, 0xf3, 0xff, 0xff, 0x9e, 0x8b, 0x6d, 0x61, 0xfe, 0x73, 0xe5, 0x4d, 0x7f,
	0x78, 0xf6, 0xbb, 0x41, 0x53, 0xf0, 0x1f, 0x5d, 0x38, 0x1c, 0x78, 0x56, 0x84, 0xb1, 0x9f, 0xdc,
	0xb4, 0x1e, 0x9d, 0xaf, 0x39, 0xe0, 0x5a, 0x0c, 0x03, 0xfb, 0x92, 0xaf, 0xbf, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xc5, 0x15, 0xe2, 0xef, 0xd9, 0x02, 0x00, 0x00,
}
